# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0002_auto_20171115_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
